sudo: required
language: cpp
branches:
  except:
  - /^\d\d\d\d\d\d\d\d\d\d\d\d\d\d-[\da-f]+$/

services:
- docker

env:
  global:
# One of them is GITHUB_TOKEN
  - secure: FlsmywHiGR6VKejCGcEd59rhvk5YI1f+FUAWfBLVxzqG4haLGT0MQwyxDr2EPS3Iu+v16nsMxHT2dwMCotC8zTPSmHUr6evE4jpNcqs+vIOAz7VLjdqwD0jweeguOR4JxL1XcgFZMAPTnoQFBFZlEOFu8OxaDjOoG7Oj0iGH+Fo=
  - secure: 89MWEONx9hRT4aMMxqTcwHVfErXx7lYuL2jirVk5qhdZhJ7GzuOgd/FjDNhyJmZxy77BcYe60vvvPsRwjst1XOUKLQ35QnIaGcN29GVhZksyW1K0qSqRr/gjf+2yDLuqZZ/OmCHDEzoNaKD3BC+weKA5J2j4qmeBEB05HKOAVZQ=
  - USE_TENSORFLOW=false

matrix:
  include:
      - os: linux
        env: DISTRIB=travis-ubuntu18.04
      - os: linux
        env: DISTRIB=travis-ubuntu18.04 USE_TENSORFLOW=true
      - os: linux
        env: DISTRIB=travis-ubuntu16.04
      - os: linux
        env: DISTRIB=debian9.4

before_script:
  - echo TRAVIS_BRANCH=$TRAVIS_BRANCH

script: 
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo BRANCH=$BRANCH
  - docker build --tag $DISTRIB --build-arg JOB_NUMBER=$TRAVIS_JOB_NUMBER --build-arg BRANCH="$BRANCH" --build-arg GITHUB_TOKEN="$GITHUB_TOKEN" --build-arg USE_TENSORFLOW="$USE_TENSORFLOW" -f ./continuous_integration/Dockerfile-$DISTRIB .

after_success:
- docker run --name travis-ubuntu18.04 -t -d travis-ubuntu18.04
- docker cp $(docker ps -n 1 -q):/usr/share/apps/lima/packages $HOME
- docker stop travis-ubuntu18.04
- docker run --name travis-ubuntu16.04 -t -d travis-ubuntu16.04
- docker cp $(docker ps -n 1 -q):/usr/share/apps/lima/packages $HOME
- docker stop travis-ubuntu16.04
- docker run --name debian9.4 -t -d debian9.4
- docker cp $(docker ps -n 1 -q):/usr/share/apps/lima/packages/ $HOME
- docker stop debian9.4

before_deploy:
- git config --local user.name "Gael de Chalendar"
- git config --local user.email "kleagg@gmail.com"
- git tag "$(git log --date=iso  -1 | grep Date | sed -e 's/Date:\ *//' -e 's/\+.*//' -e 's/[- :]//g')-$(git log --format=%h --abbrev=8 -1)" || true

deploy:
  - provider: releases
    api_key:
      secure: u0jcRYK9fsJ9ymnpU8ET5dd/DZ/rwah2WhOrfQGUkBM+VB2ASol1KCz8EMMwNQM44echMHz6LwxWM9np9vBUZZCgt/riU/vEVW7Dkmjyiwbscov7qbDmsLDdQy7LxFpEh+dA8m6U9thyWxBdtoDzDX8+3G0Oxfjf4cIa3eyAFv0=
    file_glob: true
    file: $HOME/packages/*.deb
    skip_cleanup: true
    on:
      repo: aymara/lima
      tags: false
      branches:
        except:
        - /^\d\d\d\d\d\d\d\d\d\d\d\d\d\d-[\da-f]+$/
  #- provider: script
    #script: bash continuous_integration/docker_push.sh
    #on:
      #branch: master
      #condition: $DISTRIB = travis-ubuntu18.04
